service: serverless-framework-http-API
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
          - "dynamodb:*"
          Resource: "*"

# ==================================================================================
# Functions
# ==================================================================================

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  
  addNote:
    handler: src/notes/addNote.handler
    events:
      - httpApi:
          path: /note
          method: post

# ==================================================================================
# Resources
# ==================================================================================

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
       